# Generated by Django 5.2.1 on 2025-05-29 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('assetPrefix', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('manufac', models.CharField(blank=True, max_length=100, null=True)),
                ('parts', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('dateMade', models.BigIntegerField(blank=True, null=True)),
                ('dateBuy', models.BigIntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('farmId', models.IntegerField(blank=True, null=True)),
                ('largeEquipmentVin', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicleVin', models.CharField(blank=True, max_length=100, null=True)),
                ('serialNo', models.CharField(blank=True, max_length=100, null=True)),
                ('reg', models.CharField(blank=True, max_length=100, null=True)),
                ('syncId', models.CharField(blank=True, max_length=100, null=True)),
                ('synctime', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('isDel', models.BooleanField(blank=True, default=False, null=True)),
                ('due', models.BigIntegerField(blank=True, null=True)),
                ('exp', models.BigIntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('assignedId', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('farm', models.IntegerField(blank=True, null=True)),
                ('syncId', models.CharField(blank=True, max_length=255, null=True)),
                ('synctime', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
