# Generated by Django 5.2 on 2025-05-05 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assetPrefix', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('manufac', models.CharField(max_length=100)),
                ('parts', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('dateMade', models.DateTimeField(null=True)),
                ('dateBuy', models.DateTimeField(null=True)),
                ('image', models.CharField(max_length=255)),
                ('farmId', models.IntegerField()),
                ('largeEquipmentVin', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicleVin', models.CharField(blank=True, max_length=100, null=True)),
                ('serialNo', models.CharField(blank=True, max_length=100, null=True)),
                ('reg', models.CharField(blank=True, max_length=100, null=True)),
                ('syncId', models.CharField(blank=True, max_length=100, null=True)),
                ('synctime', models.DateTimeField(null=True)),
            ],
        ),
    ]
