# Generated by Django 5.2 on 2025-05-05 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('timestamp', models.BigIntegerField()),
                ('del_field', models.BooleanField(default=False)),
                ('due', models.BigIntegerField()),
                ('exp', models.BigIntegerField()),
                ('status', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('assignedId', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('farm', models.IntegerField()),
                ('syncid', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
